language: java
deploy:
  provider: releases
  skip-cleanup: true
  api_key: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  file:"SGP_UI 1.0-SNAPSHOT.jar"
  keep-history: true
  on:
    branch: master
