language: java
addons:
  artifacts: true
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  skip-cleanup: true
  keep-history: true
  on:
    branch: master
