language: java
install:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml &&  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    branch: master
